### PR TITLE
feat: allow different solver methods for modelling

### PR DESCRIPTION
**Pull request by steven-murray**
This adds the ability to set `method=` in calls to `.fit()` on `Model` objects. The default method is the same as before (`lstsq`), but also added `qr` and `alan-qrd`, which does a much better (but not perfect) job of replicated Alan's qrd solver.

### CODE REVIEW

**Review by nmahesh1412 — COMMENTED** [review]
As a code it doesnt run into any errors. But the model fit is still different from Alan's

**Comment by steven-murray** [comment]
@nmahesh1412 I did see that there were still some differences, but it seemed much closer in my tests. Did you see this, or was it just as discrepant with Alan's models as before?

**Comment by nmahesh1412** [comment]
> @nmahesh1412 I did see that there were still some differences, but it seemed much closer in my tests. Did you see this, or was it just as discrepant with Alan's models as before?

So, I found the flags to be the EXACTLY the same with the default fitting method and the qrd fitting method

**Comment by steven-murray** [comment]
@nmahesh1412 that is strange, though it's not impossible that the fitted models are slightly different and the flags still remain the same. I'll have to dig in a bit deeper :-(

**Review by nmahesh1412 — APPROVED** [review]

**Pull request merged**
